import { notFound } from "next/navigation";
// import { getMessages } from "next-intl/server";
import { routing } from "@/i18n/routing";
import { AuthProvider } from "../../components/Providers";
import { Geist, Geist_Mono } from "next/font/google";
import "../../globals.css";
import { NextIntlClientProvider, useLocale } from "next-intl";
import LocaleProviders from "@/components/LocaleProviders";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {


  // if (!routing.locales.includes(locale)) {
  //   notFound();
  // }

  // const messages = await getMessages({ locale }  );

  return (
    <NextIntlClientProvider>
      <LocaleProviders>{children}</LocaleProviders>
    </NextIntlClientProvider>
  );
}
